const generateItemObj = (key: string) => ({
  path: key,
  title: key,
});

export const mainMenu = [
  {
    category: "mainMenu.hot",
    items: [
      generateItemObj("mainMenu.english"),
      generateItemObj("mainMenu.python"),
      generateItemObj("mainMenu.piano"),
      generateItemObj("mainMenu.japanese"),
      generateItemObj("mainMenu.bodyBuild"),
      generateItemObj("mainMenu.photography"),
      generateItemObj("mainMenu.guitar"),
      generateItemObj("mainMenu.korean"),
      generateItemObj("mainMenu.javascript"),
    ],
  },
  {
    category: "mainMenu.programming",
    items: [
      generateItemObj("mainMenu.python"),
      generateItemObj("mainMenu.javascript"),
      generateItemObj("mainMenu.leetcode"),
      generateItemObj("mainMenu.htmlCss"),
      generateItemObj("mainMenu.wordpress"),
      generateItemObj("mainMenu.frontend"),
      generateItemObj("mainMenu.backend"),
      generateItemObj("mainMenu.ios"),
      generateItemObj("mainMenu.android"),
      generateItemObj("mainMenu.cpp"),
      generateItemObj("mainMenu.java"),
    ],
  },
  {
    category: "mainMenu.language",
    items: [
      generateItemObj("mainMenu.english"),
      generateItemObj("mainMenu.englishSpeaking"),
      generateItemObj("mainMenu.toeic"),
      generateItemObj("mainMenu.ielts"),
      generateItemObj("mainMenu.toefl"),
      generateItemObj("mainMenu.japanese"),
      generateItemObj("mainMenu.korean"),
      generateItemObj("mainMenu.chinese"),
      generateItemObj("mainMenu.spanish"),
      generateItemObj("mainMenu.french"),
    ],
  },
  {
    category: "mainMenu.artAndDesign",
    items: [
      generateItemObj("mainMenu.graphicDesign"),
      {
        path: "mainMenu.illustratorAndPhotoshop",
        title: "mainMenu.illustratorAndPhotoshop",
      },
      generateItemObj("mainMenu.uiux"),
      generateItemObj("mainMenu.webDesign"),
      generateItemObj("mainMenu.computerGraphic"),
      generateItemObj("mainMenu.postProduction"),
      generateItemObj("mainMenu.painting"),
      generateItemObj("mainMenu.illustration"),
      generateItemObj("mainMenu.3d"),
      generateItemObj("mainMenu.photography"),
    ],
  },
  {
    category: "mainMenu.music",
    items: [
      generateItemObj("mainMenu.guitar"),
      generateItemObj("mainMenu.piano"),
      generateItemObj("mainMenu.singing"),
      generateItemObj("mainMenu.ukulele"),
      generateItemObj("mainMenu.musicTheory"),
    ],
  },
  {
    category: "mainMenu.sportsAndActivities",
    items: [
      generateItemObj("mainMenu.bodyBuild"),
      generateItemObj("mainMenu.weightTraining"),
      generateItemObj("mainMenu.yoga"),
      generateItemObj("mainMenu.swimming"),
      generateItemObj("mainMenu.boxing"),
      generateItemObj("mainMenu.martialArt"),
      generateItemObj("mainMenu.skateBoarding"),
      generateItemObj("mainMenu.badminton"),
    ],
  },
  {
    category: "mainMenu.business",
    items: [
      generateItemObj("mainMenu.financial"),
      generateItemObj("mainMenu.marketing"),
      generateItemObj("mainMenu.entrepreneurship"),
      generateItemObj("mainMenu.socialMedia"),
      generateItemObj("mainMenu.editor"),
      generateItemObj("mainMenu.excel"),
      generateItemObj("mainMenu.ppt"),
      generateItemObj("mainMenu.presentation"),
      generateItemObj("mainMenu.pitching"),
      generateItemObj("mainMenu.gooogleAds"),
      generateItemObj("mainMenu.seo"),
    ],
  },
  {
    category: "mainMenu.selfGrowth",
    items: [
      generateItemObj("mainMenu.entrepreneurship"),
      generateItemObj("mainMenu.investment"),
      generateItemObj("mainMenu.stock"),
      generateItemObj("mainMenu.nationalExam"),
      generateItemObj("mainMenu.health"),
      generateItemObj("mainMenu.cooking"),
      generateItemObj("mainMenu.fortuneTelling"),
    ],
  },
];
