on:
  push:
    branches:
      - main
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.12.1
      - name: Execute unit test
        run: |
          npm install
          npm run coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1
  gh_page:
    name: Deploy storybook on GH page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.12.1
      - name: build storybook
        run: |
          npm install
          STORYBOOK_MODE=PRODUCTION npm run build-storybook
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./storybook-static

          
