on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.12.1
    - name: Execute unit test
      run: |
        npm install
        npm run coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TUTY_SONAR_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  gh_page:
    name: Deploy storybook on GH page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.12.1
      - name: build storybook
        run: |
          npm install
          STORYBOOK_MODE=PRODUCTION npm run build-storybook
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./storybook-static

          
